name: Deploy React App to ACR

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Get secrets from Azure Key Vault
      uses: azure/get-keyvault-secrets@v1
      with:
        keyvault: ${{ secrets.AZURE_KEYVAULT_NAME }}
        secrets: 'ACR-USERNAME, ACR-PASSWORD, ACR-URL'
      id: getSecrets

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to ACR
      uses: docker/login-action@v1
      with:
        registry: ${{ steps.getSecrets.outputs.ACR-URL }}
        username: ${{ steps.getSecrets.outputs.ACR-USERNAME }}
        password: ${{ steps.getSecrets.outputs.ACR-PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ steps.getSecrets.outputs.ACR-URL }}/my-react-app:${{ github.sha }}