# This workflow will build and push a node.js application to Azure Container Registry (ACR) and deploy it to an Azure Web App when a commit is pushed to your default branch.

name: Build and Deploy to Azure

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: react-app    # set this to your application's name
  NODE_VERSION: '20.0.0'                # set this to the node version to use
  AZURE_KEYVAULT_NAME: your-keyvault-name  # set this to your Azure Key Vault name

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: npm install and build
      run: |
        npm install
        npm run build --if-present

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Get secrets from Azure Key Vault
      uses: azure/get-keyvault-secrets@v1
      with:
        keyvault: ${{ env.AZURE_KEYVAULT_NAME }}
        secrets: 'ACR-USERNAME, ACR-PASSWORD, ACR-URL'
      id: getSecrets

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to ACR
      uses: docker/login-action@v1
      with:
        registry: ${{ steps.getSecrets.outputs.ACR-URL }}
        username: ${{ steps.getSecrets.outputs.ACR-USERNAME }}
        password: ${{ steps.getSecrets.outputs.ACR-PASSWORD }}

    - name: Build and push Docker image to ACR
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ steps.getSecrets.outputs.ACR-URL }}/${{ env.AZURE_WEBAPP_NAME }}:${{ github.sha }}

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        images: '${{ steps.getSecrets.outputs.ACR-URL }}/${{ env.AZURE_WEBAPP_NAME }}:${{ github.sha }}'

    - name: Azure logout
      run: |
        az logout
